web:
    # build: 
    #     context: .
    #     dockerfile: WebApplication/Dockerfile
    image: vechtomov/vktracker
    ports:
        - "7777:5555"
    links:
        - sqlserver
    environment: 
        - VK_APPID=${VK_APPID}
        - VK_LOGIN=${VK_LOGIN}
        - VK_PASSWORD=${VK_PASSWORD}
        - SQL_SERVER_NAME=sqlserver
        - SQL_SA_PASSWORD=${SQL_SA_PASSWORD}
    cpu_shares: 100
    mem_limit: 262144000
sqlserver:
    image: "microsoft/mssql-server-linux"
    environment:
        SA_PASSWORD: ${SQL_SA_PASSWORD}
        ACCEPT_EULA: "Y"
    ports: 
        - "1434:1433"
    cpu_shares: 100
    mem_limit: 262144000