version: "3.1"
services:
    web:
        image: vechtomov/vktracker
        ports:
            - "7777:5555"
        cpu_shares: 100
        mem_limit: 262144000
        links:
            - mongodb
        environment:
            VkAnalyzerSettings__AppId: ${VK_APPID}
            VkAnalyzerSettings__VkUserLogin: ${VK_LOGIN}
            VkAnalyzerSettings__VkUserPassword: ${VK_PASSWORD}
            MongoConnectionSettings__Host: mongodb
            MongoConnectionSettings__Port: 27017
            MongoConnectionSettings__Database: VkTracker
            SqlRepositorySettings__Connection: Server=sqlserver;Initial Catalog=VkTrackerDb;User ID=sa;Password=${SQL_SA_PASSWORD}
    mongodb:
        image: mongo
        ports:
            - 27000:27017
        cpu_shares: 100
        mem_limit: 262144000
        volumes:
            - mongodbvolume:/data/db

volumes:
    mongodbvolume: